/* Generated By:JJTree: Do not edit this line. ASTprintMessagesError.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintMessagesError extends SimpleNode {
  public ASTprintMessagesError(int id) {
    super(id);
  }

  public ASTprintMessagesError(parserGrammar p, int id) {
    super(p, id);
  }
}
/* JavaCC - OriginalChecksum=50ffcac6bab8c0888d0253c0ec53c7b3 (do not edit this line) */
