/* Generated By:JavaCC: Do not edit this line. parserGrammarTreeConstants.java Version 6.0_1 */
public interface parserGrammarTreeConstants
{
  public int JJTSKIPTO = 0;
  public int JJTSKIPTO_DO_NOT_CONSUME_LAST = 1;
  public int JJTPRINTMESSAGESERROR = 2;
  public int JJTMODULE = 3;
  public int JJTDECLARATION = 4;
  public int JJTFUNCTION = 5;
  public int JJTVARLIST = 6;
  public int JJTARRAYELEMENT = 7;
  public int JJTSCALARELEMENT = 8;
  public int JJTSTMTLST = 9;
  public int JJTSTMT = 10;
  public int JJTASSIGN = 11;
  public int JJTLHS = 12;
  public int JJTRHS = 13;
  public int JJTARRAYSIZE = 14;
  public int JJTTERM = 15;
  public int JJTEXPRTEST = 16;
  public int JJTWHILE = 17;
  public int JJTIF = 18;
  public int JJTCALLSTMT = 19;
  public int JJTCALL = 20;
  public int JJTARGUMENTLIST = 21;
  public int JJTARGUMENT = 22;
  public int JJTARRAYACCESS = 23;
  public int JJTSCALARACCESS = 24;
  public int JJTINDEX = 25;
  public int JJTERRORBLOCK = 26;


  public String[] jjtNodeName = {
    "skipto",
    "skipto_do_not_consume_last",
    "printMessagesError",
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "ScalarElement",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "CallStmt",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "ErrorBlock",
  };
}
/* JavaCC - OriginalChecksum=e126b6d61171d161f0ac008fa7458c15 (do not edit this line) */
