/* Generated By:JJTree: Do not edit this line. ASTErrorBlock.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTErrorBlock extends SimpleNode {
  public ASTErrorBlock(int id) {
    super(id);
  }

  public ASTErrorBlock(parserGrammar p, int id) {
    super(p, id);
  }

  @Override
  public boolean analyseContent(SymbolsTable currentTable){
    SymbolsTable symbolsTable = new SymbolsTable(currentTable);

    for(int i=0; i < jjtGetNumChildren();i++){
      jjtGetChild(i).analyse(symbolsTable);
    }

    return true;
  }

}
/* JavaCC - OriginalChecksum=028e30976a38d0ecf00d0d9ff7b0dcd9 (do not edit this line) */
