/* Generated By:JJTree: Do not edit this line. ASTCallStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCallStmt extends SimpleNode {
	
	private String name;
	private String nameId2;
	
  public ASTCallStmt(int id) {
    super(id);
  }

  public ASTCallStmt(parserGrammar p, int id) {
    super(p, id);
  }
  
  public String getName() {
	  return name;
  }
  
  public String getNameId2() {
	  return nameId2;
  }
  
  public void setName(String name) {
	  this.name = name;
  }
  
  public void setNameId2(String name) {
	  this.nameId2 = name;
  }
  
  public String toString() {
	  String test = super.toString();
			  
	if(name != null)
	  test+= " " + name;
	
	if(nameId2 != null)
	  test+= " " + nameId2;
	  
	  return test;
  }

}
/* JavaCC - OriginalChecksum=1172cce7e76875502efd4a41002c39ad (do not edit this line) */
