/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
	private String name;
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(parserGrammar p, int id) {
    super(p, id);
  }
  
  public String getName() {
	  return name;
  }
  
  public void setName(String name) {
	  this.name = name;
  }
  
  public String toString() {
	  String test;
	  
	  test = super.toString() + " " + name;
	  
	  return test;
  }
  
}
/* JavaCC - OriginalChecksum=1fa68f33e8079fb3050f029ab6fbfb70 (do not edit this line) */
