/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
      super(id);
    }

    public ASTAssign(parserGrammar p, int id) {
      super(p, id);
    }

    @Override
    public boolean analyse(SymbolsTable currentTable){
      boolean returnValue;

      System.out.println("Analyse Rhs of Assign");
      returnValue = jjtGetChild(1).analyseRhs(currentTable);
      System.out.println("Analyse Lhs of Assign");
      jjtGetChild(0).analyseLhs(currentTable, returnValue);

      return true;
    }
  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b3475a7f97d89ed9e8c02178ae45c09 (do not edit this line) */
