/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(parserGrammar p, int id) {
    super(p, id);
  }

  @Override
  public boolean analyse(SymbolsTable currentTable){
    boolean returnValue;

    System.out.println("Analyse Rhs");
    returnValue = jjtGetChild(1).analyseRhs(currentTable);
    System.out.println("Analyse Lhs");
    jjtGetChild(0).analyseLhs(currentTable, returnValue);

    return true;
  }

}
/* JavaCC - OriginalChecksum=705caf986bd730600047406af35eda0d (do not edit this line) */
