/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccess extends SimpleNode {
  private String name;


  public ASTArrayAccess(int id) {
    super(id);
  }

  public ASTArrayAccess(parserGrammar p, int id) {
    super(p, id);
  }

  public String getName() {
	  return name;
  }

  public void setName(String name) {
	  this.name = name;
  }

  public String toString() {
	  String test;

	  test = super.toString() + " " + name;

	  return test;
  }

  @Override
  public boolean analyse(SymbolsTable currentTable){

    if(currentTable.returnSymbol(name) != null){
			System.out.println("This value's array exists on Symbols Table");

      return true;
		}

    System.out.println("This value's array doesn't exist on Symbols Table");
    return false;

  }

	public boolean analyseRhs(SymbolsTable currentTable){
		System.out.println("Analyse the right part of ArrayAccess");

		return true;
	}

	public boolean analyseLhs(SymbolsTable currentTable, boolean value){
		Symbol symbol = currentTable.returnSymbol(name);

		if(symbol == null){
			System.out.println("Symbol is null on ArrayAccess");
			currentTable.putOnHashMap(new Symbol("ArrayAccess",name,value));
		}

		else{
			//verificar se o valor de Rhs não é escalar OU se o símbolo não é um array
			if(value != true || symbol.isScalar() == true)
				System.out.println("Semantics Error!");
		}

		return true;

	}


  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=364523e5797c56547e69181471d7f9c7 (do not edit this line) */
