/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayElement extends SimpleNode {
	private String name;


  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(parserGrammar p, int id) {
    super(p, id);
  }

  public String getName() {
	  return name;
  }

  public void setName(String name) {
	  this.name = name;
  }

  public String toString() {
	  String test;

	  test = super.toString() + " " + name;

	  return test;
  }

  @Override
  public boolean analyse(SymbolsTable currentTable){
    currentTable.putOnHashMap(new Symbol("ArrayElement",name,false));
    System.out.println("ArrayElement: ");
    System.out.println(currentTable);
    return true;
  }

}
/* JavaCC - OriginalChecksum=d28682a6d6dbfcfccc55c199ddf1b7a2 (do not edit this line) */
