/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(parserGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d122d15cdad671fb1b2de6b397c596bb (do not edit this line) */
