/* Generated By:JJTree: Do not edit this line. ASTprintMessagesError.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTprintMessagesError extends SimpleNode {
  public ASTprintMessagesError(int id) {
    super(id);
  }

  public ASTprintMessagesError(parserGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=de31f719605ffffae2301308c03628db (do not edit this line) */
