/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(parserGrammar p, int id) {
    super(p, id);
  }

  @Override
  public boolean analyseContent(SymbolsTable currentTable){
    System.out.println("Analyse children of Stmt");

    for(int i=0; i < jjtGetNumChildren();i++){
      jjtGetChild(i).analyse(currentTable);
    }

    return true;
  }
  
}
/* JavaCC - OriginalChecksum=1750e394b2fe4f32b2e8864b15ac7904 (do not edit this line) */
