/* Generated By:JJTree: Do not edit this line. ASTskipto_do_not_consume_last.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto_do_not_consume_last extends SimpleNode {
  public ASTskipto_do_not_consume_last(int id) {
    super(id);
  }

  public ASTskipto_do_not_consume_last(parserGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=00c3cedef5d71f9ddd31764586f793da (do not edit this line) */
