/* Generated By:JJTree: Do not edit this line. ASTskipto.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto extends SimpleNode {
  public ASTskipto(int id) {
    super(id);
  }

  public ASTskipto(parserGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebf9e85eb765ab0b131bbd90c8761dc1 (do not edit this line) */
