/* Generated By:JJTree: Do not edit this line. ASTScalarElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarElement extends SimpleNode {
  private String name;

  public ASTScalarElement(int id) {
    super(id);
  }

  public ASTScalarElement(parserGrammar p, int id) {
    super(p, id);
  }

  public String getName() {
	  return name;
  }

  public void setName(String name) {
	  this.name = name;
  }

  public String toString() {
	  String test;

	  test = super.toString() + " " + name;

	  return test;
  }

  @Override
  public boolean analyse(SymbolsTable currentTable){
    currentTable.putOnHashMap(new Symbol("ScalarElement",name,true));
    System.out.println("ScalarElement pos na hashmap ");
    return true;
  }


  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80ba0922d318f987172c8d7c0b639db8 (do not edit this line) */
