/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
      super(id);
    }

    public ASTVarlist(parserGrammar p, int id) {
      super(p, id);
    }

    @Override
    public boolean analyseContent(SymbolsTable currentTable){
      System.out.println("Analyse the children of Varlist");

      for(int i=0; i < jjtGetNumChildren();i++){
        jjtGetChild(i).analyse(currentTable);
      }

      return true;
    }
    
  /** Accept the visitor. **/
  public Object jjtAccept(parserGrammarVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7243b5cf688c356662166cb710748e7e (do not edit this line) */
