/* Generated By:JavaCC: Do not edit this line. parserGrammarTreeConstants.java Version 6.0_1 */
public interface parserGrammarTreeConstants
{
  public int JJTSKIPTO = 0;
  public int JJTSKIPTO_DO_NOT_CONSUME_LAST = 1;
  public int JJTPRINTMESSAGESERROR = 2;
  public int JJTMODULE = 3;
  public int JJTDECLARATION = 4;
  public int JJTFUNCTION = 5;
  public int JJTVOID = 6;
  public int JJTARRAYELEMENT = 7;
  public int JJTSCALARELEMENT = 8;
  public int JJTRHS = 9;
  public int JJTARRAYSIZE = 10;
  public int JJTTERM = 11;
  public int JJTEXPRTEST = 12;
  public int JJTIF = 13;
  public int JJTCALLSTMT = 14;
  public int JJTCALL = 15;
  public int JJTARGUMENTLIST = 16;
  public int JJTARGUMENT = 17;
  public int JJTARRAYACCESS = 18;
  public int JJTSCALARACCESS = 19;
  public int JJTINDEX = 20;
  public int JJTERRORBLOCK = 21;


  public String[] jjtNodeName = {
    "skipto",
    "skipto_do_not_consume_last",
    "printMessagesError",
    "Module",
    "Declaration",
    "Function",
    "void",
    "ArrayElement",
    "ScalarElement",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "If",
    "CallStmt",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "ErrorBlock",
  };
}
/* JavaCC - OriginalChecksum=87fd40587d0504393f17f199ddbdaa85 (do not edit this line) */
