/* Generated By:JJTree: Do not edit this line. ASTskipto_do_not_consume_last.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto_do_not_consume_last extends SimpleNode {
  public ASTskipto_do_not_consume_last(int id) {
    super(id);
  }

  public ASTskipto_do_not_consume_last(parserGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05dc02cfb25932de49a2e0db4731014b (do not edit this line) */
