/* Generated By:JavaCC: Do not edit this line. parserGrammarTreeConstants.java Version 5.0 */
public interface parserGrammarTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTSTMTLST = 6;
  public int JJTSTMT = 7;
  public int JJTASSIGN = 8;
  public int JJTLHS = 9;
  public int JJTRHS = 10;
  public int JJTARRAYSIZE = 11;
  public int JJTTERM = 12;
  public int JJTEXPRTEST = 13;
  public int JJTWHILE = 14;
  public int JJTIF = 15;
  public int JJTCALL = 16;
  public int JJTARGUMENTLIST = 17;
  public int JJTARGUMENT = 18;
  public int JJTARRAYACCESS = 19;
  public int JJTSCALARACCESS = 20;
  public int JJTINDEX = 21;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "ScalarElement",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=9e3fe0c78803b25c69e9b08ab141e700 (do not edit this line) */
