/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
        super(id);
      }

  public ASTAssign(parserGrammar p, int id) {
    super(p, id);
  }

  @Override
  public boolean analyse(SymbolsTable currentTable){
    boolean returnValue;

    System.out.println("Analyse Rhs of Assign");
    returnValue = jjtGetChild(1).analyseRhs(currentTable);
    System.out.println("Analyse Lhs of Assign");
    jjtGetChild(0).analyseLhs(currentTable, returnValue);

    return true;
  }

  public String convertToByteCodes(MapVariables data, int loop_no){
    String line = "";
    line += jjtGetChild(1).convertToByteCodes(data, loop_no);

    line += jjtGetChild(0).convertToByteCodes(data, loop_no);

    return line;
  }
}
/* JavaCC - OriginalChecksum=e20e022e8c7e693a216dbfcbaefa6bca (do not edit this line) */
