/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndex extends SimpleNode {
  private String name;

      public ASTIndex(int id) {
        super(id);
      }

      public ASTIndex(parserGrammar p, int id) {
        super(p, id);
      }

      public String getName() {
    	  return name;
      }

      public void setName(String name) {
    	  this.name = name;
      }

      public String toString() {
    	  String test;

    	  test = super.toString() + " " + name;

    	  return test;
      }


}
/* JavaCC - OriginalChecksum=1d244425685d177203b0429512a9d965 (do not edit this line) */
