/* Generated By:JJTree: Do not edit this line. ASTskipto.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTskipto extends SimpleNode {
  public ASTskipto(int id) {
    super(id);
  }

  public ASTskipto(parserGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f63e695f8e9dfae28d6aac3c2a09ee2a (do not edit this line) */
