/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  private String name;
	private String nameInteger;


  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(parserGrammar p, int id) {
    super(p, id);
  }

  public String getName() {
	  return name;
  }

  public String getNameInteger() {
	  return nameInteger;
  }

  public void setName(String name) {
	  this.name = name;
  }

  public void setNameInteger(String name) {
	  this.nameInteger = name;
  }

  public String toString() {
	  String test = super.toString();

	if(name != null)
	  test+= " " + name;

	if(nameInteger != null)
	  test+= " " + nameInteger;

	  return test;
  }

  public int analyse(SymbolsTable currentTable){

    return analyseContent(currentTable);
  }

  @Override
  public int analyseContent(SymbolsTable currentTable){
		System.out.println("Analyse children of Declaration");
    int b=0;

    for(int i=0; i < jjtGetNumChildren();i++){
      if(jjtGetChild(i).analyse(currentTable)==-1)
        b=-1;
    }

    return b;
  }

  public String convertToByteCodes(MapVariables data){
    String line = "";
    String aux = "";

    aux += jjtGetChild(0).convertToByteCodes(data);
    if(jjtGetNumChildren() == 2 && jjtGetChild(1) != null) {
      String[] split = aux.split(" I");
      line = split[0] + " [I\n";
      String[] temp = split[0].split(" ");
      String name = temp[2];
      for(int i = 0; i < data.globalVariables.size();i++) {
        if(data.globalVariables.get(i).getSymbolName().equals(name)) {
          data.globalVariables.get(i).setSymbolType("GlobalArray");
          data.globalVariables.get(i).setIsScalar(false);
        }
      }
    }
    else
      line = aux;
    return line;
  }

}
/* JavaCC - OriginalChecksum=7937f9650d27ed34a54fb92c15537b29 (do not edit this line) */
