/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(parserGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f305dfe9858887293df063a593fcd9db (do not edit this line) */
