/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
	private String name;

	
  public ASTArraySize(int id) {
    super(id);
  }

  public ASTArraySize(parserGrammar p, int id) {
    super(p, id);
  }
  
  public String getName() {
	  return name;
  }
  
  public void setName(String name) {
	  this.name = name;
  }
  
  public String toString() {
	  String test = super.toString();
		
	  if(name != null)
		  test+= " " + name;
	  
	  return test;
  }

}
/* JavaCC - OriginalChecksum=74d92097ac7f75498953afd4f4b6a954 (do not edit this line) */
